---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-24 11:20 p.m.
---

local CTF_TEAM_CONSTANTS = use('scripts/constants/CTFTeamConstants');

local function _addEventListener(world, prefab, cb)
    world:ListenForEvent(CTF_TEAM_CONSTANTS.PLAYER_REGISTERED_EVENT, function(_, ctfPlayer)
        local player = ctfPlayer:getPlayer();
        if player.prefab == prefab then
            cb(player, ctfPlayer);
        end
    end);
end

local function CTFCharacterPostInit(prefab, cb)
    if _G.TheWorld then
        _addEventListener(_G.TheWorld, prefab, cb);
    else
        AddPrefabPostInit('world', function(inst)
            _addEventListener(inst, prefab, cb);
        end);
    end
end

return CTFCharacterPostInit;
