---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-22 7:05 p.m.
---

local function CTFClassPatcher(class, fn)
    local ctor = class._ctor
    class._ctor = function (self, ...)
        fn(self, ctor, ...);
    end
end

return CTFClassPatcher;
