---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-16 8:44 p.m.
---

AddPrefabPostInit('armorskeleton', function(inst)
    if inst.components and inst.components.fueled then
        inst.components.fueled.fueltype = FUELTYPE.POOP;
    end
end);
