---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-23 5:10 p.m.
---

modimport('scripts/prefabs/patcher/CTFPrefabPatcher');
modimport('scripts/teams/CTFTeamManager');

CTFPrefabPatcher:registerPrefabPatcher('bishop', function(inst, data)
    if TheWorld.ismastersim then
        inst.components.lootdropper.chanceloottable = false;
        inst.components.lootdropper:SetLoot({'goldnugget', 'goldnugget', 'goldnugget', 'goldnugget', 'goldnugget'});
        if data.ctf_team then
            CTFTeamManager:registerTeamObject(inst, data);
        end
    end
end)
