---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-23 5:10 p.m.
---
local require = _G.require;
local clockwork_common = require('prefabs/clockwork_common');

local OldOnAttacked = clockwork_common.OnAttacked;
clockwork_common.OnAttacked = function(inst, data)
    local currentTarget = inst.components.combat.target;
    if not currentTarget or not currentTarget:IsValid() or currentTarget.components.health:IsDead() then
        OldOnAttacked(inst, data);
    end
end

CTFPrefabPatcher:registerPrefabPatcher('bishop_nightmare', function(inst, data)
    if TheWorld.ismastersim then
        CTFPrefabPatcher:patchStats(inst, data);

        if inst.components then
            if inst.components.sleeper then
                inst.components.sleeper:SetSleepTest(function() return false end);
            end

            if inst.components.combat then
                local OldRetargetFunction = inst.components.combat.targetfn;
                inst.components.combat:SetRetargetFunction(0.25, OldRetargetFunction);
            end

            if inst.components.freezable then
                inst.components.freezable:SetResistance(5);
                inst.components.freezable:SetDefaultWearOffTime(5);
            end
        end

        if data.ctf_team then
            CTFTeamManager:registerTeamObject(inst, data);
        end
    end
end)
