---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-16 6:49 p.m.
---

CTFPrefabPatcher = {};

function CTFPrefabPatcher:registerPrefabPatcher(prefab, patcher)
    AddPrefabPostInit(prefab, function(instance)
        local OldOnLoad = instance.OnLoad or nil;
        instance.OnLoad = function(inst, data)
            if data and data.ctf_team then
                --print(inst.prefab, 'CTF_TEAM', data.ctf_team);
                -- CTFTeamManager:registerTeamObject(inst, data);
                patcher(inst, data);
            end
            if OldOnLoad ~= nil then
                OldOnLoad(inst, data);
            end
        end
    end);
end
