---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-23 1:19 p.m.
---

AddPrefabPostInit('multiplayer_portal', function(inst)
    if TheWorld.ismastersim then
        inst:DoTaskInTime(0, function()
            SpawnPrefab("multiplayer_portal_moonrock").Transform:SetPosition(inst.Transform:GetWorldPosition());
            inst:Remove();
        end);
    end
end);
