---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-16 7:00 p.m.
---

modimport('scripts/prefabs/patcher/CTFPrefabPatcher');
modimport('scripts/teams/CTFTeamManager');

CTFPrefabPatcher:registerPrefabPatcher('piggyback', function(inst, data)
    if TheWorld.ismastersim then
        print('PIGYBACK ================================================================')
        inst.components.equippable.walkspeedmult = 0.45;
        CTFTeamManager:registerTeamObject(inst, data);
    end
end)
