---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-16 7:00 p.m.
---
local require = _G.require;
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');

CTFPrefabPatcher:registerPrefabPatcher('piggyback', function(inst, data)
    if TheWorld.ismastersim then
        if data.ctf_team then
            CTFTeamManager:registerTeamObject(inst, data);
        end
    end
end)
