---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-23 5:09 p.m.
---
CTFPrefabPatcher:registerPrefabPatcher('pigtorch', function(inst, data)
    if inst.components then
        if inst.components.spawner then
            inst.components.spawner:Configure('pigguard', TUNING.TOTAL_DAY_TIME * 2);
            inst.components.spawner:SetOnlySpawnOffscreen(false);
        end

        if inst.components.fueled then
            inst.components.fueled:SetDepletedFn(function()
                inst.components.fueled:SetPercent(1);
            end);
        end
    end

    if TheWorld.ismastersim then
        if data.ctf_team then
            CTFTeamManager:registerTeamObject(inst, data);
        end
    end
end)
