---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-23 5:09 p.m.
---
local require = _G.require;
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');

modimport('scripts/prefabs/patcher/CTFPrefabPatcher');
modimport('scripts/teams/CTFTeamManager');

CTFPrefabPatcher:registerPrefabPatcher('pigtorch', function(inst, data)
    if inst.components and inst.components.spawner then
        inst.components.spawner.delay = TUNING.TOTAL_DAY_TIME;
    end

    if TheWorld.ismastersim then
        if data.ctf_team then
                CTFTeamManager:registerTeamObject(inst, data);
        end
    end
end)
