---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-16 8:42 p.m.
---

FUELTYPE.POOP = 'POOP';

AddPrefabPostInit('poop', function(inst)
    if inst.components and inst.components.fuel then
        inst.components.fuel.fueltype = FUELTYPE.POOP;
        inst.components.fuel:SetOnTakenFn(nil);
    end
end);
