---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-20 12:39 p.m.
---

local CTF_SKELETON_MAX_HEALTH = 200;

AddPrefabPostInit('skeleton_player', function(inst)
    local OldSetSkeletonAvatarData = inst.SetSkeletonAvatarData;
    inst.SetSkeletonAvatarData = function(f_inst, client_obj)
        local team = client_obj and CTFTeamManager:getPlayerTeam(client_obj.userid) or nil;
        if team then
            team:registerObject(f_inst, nil);
        end

        if f_inst.components then
            if not f_inst.components.health then
                f_inst:AddComponent('health');
            end
            f_inst.components.health:SetMaxHealth(CTF_SKELETON_MAX_HEALTH);

            if not f_inst.components.combat then
                f_inst:AddComponent('combat');
            end
            f_inst.components.combat.onkilledbyother = function (ff_inst, attacker)
                f_inst.components.workable.onfinish(ff_inst);
                if f_inst.data and f_inst.data.ctf_despawnTimer then
                    f_inst.data.ctf_despawnTimer:Cancel();
                    f_inst.data.ctf_despawnTimer = nil;
                end
            end

            if not f_inst.components.lootdropper then
                f_inst:AddComponent('lootdropper');
            end
            f_inst.components.lootdropper:SetLoot({ 'goldnugget' })
            f_inst.components.lootdropper.numrandomloot = 0

            -- schedule auto death
            if not f_inst.data then
                f_inst.data = {};
            end

            f_inst.data.ctf_despawnTimer = f_inst:DoTaskInTime(TUNING.TOTAL_DAY_TIME, function()
                f_inst.components.combat.onkilledbyother = nil;
                f_inst.components.health:Kill();
            end);
        end

        OldSetSkeletonAvatarData(f_inst, client_obj);
    end
end);
