---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-17 1:47 p.m.
---

AddPrefabPostInit('spider', function(inst)
    if TheWorld.ismastersim then
        inst.components.lootdropper:SetLoot({'goldnugget'});
    end
end);
