---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-17 1:43 p.m.
---

AddPrefabPostInit('spiderden', function(inst)
    if TheWorld.ismastersim then
        inst.components.lootdropper:SetLoot({'goldnugget', 'goldnugget'});
    end
end);

AddPrefabPostInit('spiderden_2', function(inst)
    if TheWorld.ismastersim then
        inst.components.lootdropper:SetLoot({'goldnugget', 'goldnugget', 'goldnugget', 'goldnugget'});
    end
end);

AddPrefabPostInit('spiderden_3', function(inst)
    if TheWorld.ismastersim then
        inst.components.lootdropper:SetLoot({'goldnugget', 'goldnugget', 'goldnugget', 'goldnugget', 'goldnugget', 'goldnugget'});
    end
end);
