---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-17 1:45 p.m.
---

AddPrefabPostInit('spiderqueen', function(inst)
    if TheWorld.ismastersim then
        inst.components.lootdropper:SetLoot({
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
            'goldnugget',
        });
    end
end);
