---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-23 5:13 p.m.
---

modimport('scripts/prefabs/patcher/CTFPrefabPatcher');
modimport('scripts/teams/CTFTeamManager');

AddPrefabPostInit('tallbird', function(inst)
    if TheWorld.ismastersim then
        inst.components.lootdropper:SetLoot({'goldnugget', 'goldnugget', 'goldnugget'});
    end
end);
