---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-17 1:11 p.m.
---
local require = _G.require;
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');

modimport('scripts/prefabs/patcher/CTFPrefabPatcher');
modimport('scripts/teams/CTFTeamManager');

CTFPrefabPatcher:registerPrefabPatcher('wasphive', function(inst, data)
    if TheWorld.ismastersim then
        if data.ctf_team then
            TheWorld:ListenForEvent(CTF_TEAM_CONSTANTS.PLAYER_CONNECTED_EVENT, function()
                CTFTeamManager:registerTeamObject(inst, data);
            end);
        end
    end

    if inst.components and inst.components.health then
        inst.components.health:SetMaxHealth(CTF_TEAM_CONSTANTS.WASPHIVE_HEALTH);
    end
end)
