---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-07 9:54 a.m.
---

local wormholeList = {};

CTFPrefabPatcher:registerPrefabPatcher('wormhole', function(inst, data)
    if inst.components and inst.components.teleporter and data and data.ctf_wormhole and data.ctf_wormhole_target then
        wormholeList[data.ctf_wormhole] = inst;
        if wormholeList[data.ctf_wormhole_target] then
            inst.components.teleporter.targetTeleporter = wormholeList[data.ctf_wormhole_target];
            wormholeList[data.ctf_wormhole_target].components.teleporter.targetTeleporter = inst;
        end
    end
end);
