---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-05 9:39 a.m.
---
local require = _G.require;
local inventory = require('init/player_inventory');
local ShowWelcomeScreen = require('screens/CTFInstructionsPopup');
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');
local CTFTeamMarker = use('scripts/teams/CTFTeamMarker');

AddPrefabPostInit('ctf_player_net', function(inst)
    if not TheWorld.ismastersim then
        inst:ListenForEvent(inst.player.event, function()
            local player = inst.player.var:value();
            CTFPlayer(player, inst);
        end);
    end
end);

CTFPlayer = Class(function(self, player, net)
    print('======================================== CTFPlayer', player, net);
    -- this is supposed to run on both server and client
    self.player = player;
    self.net = net or self:createPlayerNet(player);

    self:initNet();
    self:initCommon();
    if TheWorld.ismastersim and self.player then
        self:initMaster();
    end
end);

function CTFPlayer:kill()
    print('============================================ CTFPlayer:kill');
end

function CTFPlayer:initCommon()
    --CTFTeamManager:registerCTFPlayer(self);
end

function CTFPlayer:initMaster()
    local player = self.player;
    print('======================================== CTFPlayer:initMaster', player);
    inventory.removeAllItems(player);
    inventory.initializeInventory(player);

    local function OnPlayerSpawned(f_player)
        print('======================================== OnPlayerSpawned', f_player);
        f_player:RemoveEventCallback('colourtweener_end', OnPlayerSpawned);
        self.net.spawned.var:push();
    end
    player:ListenForEvent('colourtweener_end', OnPlayerSpawned);
end

function CTFPlayer:initNet()
    if not TheNet:IsDedicated() then
        print('======================================== initNet');
        self:initNetEvents();
    end
end

function CTFPlayer:initNetEvents()
    print('======================================== initNetEvents');
    if self.player == _G.ThePlayer then
        print('======================================== _G.ThePlayer');
        self.net:ListenForEvent(self.net.spawned.event, function() self:netHandleSpawnedEvent() end);
        --self.player:DoTaskInTime(5, function() self:netHandleSpawnedEvent() end);
    end
end

function CTFPlayer:netHandleSpawnedEvent()
    print('======================================== netHandleSpawnedEvent');
    ShowWelcomeScreen(function()
        SendModRPCToServer(MOD_RPC[CTF_TEAM_CONSTANTS.RPC_NAMESPACE][CTF_TEAM_CONSTANTS.RPC.PLAYER_JOINED_CTF]);
    end);
end

function CTFPlayer:getTeamID()
    return self.net.team_id.var:value();
end

function CTFPlayer:setTeamID(teamID)
    self.net.team_id.var:set(teamID);
end

function CTFPlayer:isReady()
    return self.net.ready.var:value();
end

function CTFPlayer:setReady(ready)
    self.net.ready.var:set(ready);
    if TheWorld.ismastersim then
        CTFTeamManager:playerReadyUpdated(self);
    end
end

function CTFPlayer:createPlayerNet(player)
    print('=================================================== createPlayerNet', player);
    local net = player:SpawnChild('ctf_player_net');

    player:DoTaskInTime(0, function()
        net.player.var:set(player);
    end);

    return net;
end

_G.CTFPlayer = CTFPlayer;
