---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-05 9:39 a.m.
---
local require = _G.require;
local inventory = require('init/player_inventory');
local ShowWelcomeScreen = require('screens/CTFInstructionsPopup');
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');
local CTFTeamMarker = use('scripts/teams/CTFTeamMarker');

CTFPlayer = Class(function(self, player)
    -- this is supposed to run on both server and client
    self.player = player;
    self.net = nil;
    self.marker = nil;

    self.net = self.player:SpawnChild('ctf_player_net');

    self:initNet();
    self:initCommon();
    if TheWorld.ismastersim then
        self:initMaster();
    end
end);

function CTFPlayer:kill()
    print('============================================ CTFPlayer:kill');
end

function CTFPlayer:initCommon()
    CTFTeamManager:registerCTFPlayer(self);
end

function CTFPlayer:initMaster()
    local player = self.player;
    inventory.removeAllItems(player);
    inventory.initializeInventory(player);

    local function OnPlayerSpawned(f_player)
        f_player:RemoveEventCallback('colourtweener_end', OnPlayerSpawned);
        self.net.spawn_event:push();
        self.marker = CTFTeamMarker(self.player);
        local teamID = self:getTeamID();
        if teamID ~= 0 then
            self.marker:setHue(CTFTeam:getTeamColor(teamID));
        end
    end
    player:ListenForEvent('colourtweener_end', OnPlayerSpawned);
end

function CTFPlayer:initNet()
    if not TheNet:IsDedicated() then
        self:initNetEvents();
    end
end

function CTFPlayer:initNetEvents()
    if self.player == _G.ThePlayer then
        self.net:ListenForEvent('spawn_event', function() self:netHandleSpawnedEvent() end);
    end
end

function CTFPlayer:netHandleSpawnedEvent()
    ShowWelcomeScreen(function()
        SendModRPCToServer(MOD_RPC[CTF_TEAM_CONSTANTS.RPC_NAMESPACE][CTF_TEAM_CONSTANTS.RPC.PLAYER_JOINED_CTF]);
    end);
end

function CTFPlayer:getTeamID()
    return self.net.team_id:value();
end

function CTFPlayer:setTeamID(teamID)
    self.net.team_id:set(teamID);
end

function CTFPlayer:isReady()
    return self.net.ready:value();
end

function CTFPlayer:setReady(ready)
    self.net.ready:set(ready);
    if TheWorld.ismastersim then
        CTFTeamManager:playerReadyUpdated(self);
    end
end
