---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-22 3:58 p.m.
---

local CTF_CONSTANTS = {
    EXCLUDE_PREFIX_TAG = 'CTF_EXCLUDE_',

    MINION_PREFABS = { 'spider', 'spider', 'spider', 'spider_warrior' },

    TEAM_FLAG_PREFAB = 'piggyback',

    TEAM_PREFIX_TAG = 'CTF_TEAM_',
    TEAM_FLAG_TAG = 'CTF_TEAM_FLAG',
    TEAM_ITEM_TAG = 'CTF_TEAM_ITEM',
    TEAM_PLAYER_TAG = 'CTF_TEAM_PLAYER',
    TEAM_MINION_TAG = 'CTF_TEAM_MINION',
    TEAM_MINION_SPAWNER_TAG = 'CTF_TEAM_MINION_SPAWNER',

    TEAM_COLORS = {
        { 0.666, 0.407, 0.784, 1 },
        { 0.996, 1, 0.454, 1 },
        { 0.403, 0.756, 0.764, 1 },
        { 0.996, 0.674, 0.407, 1 },
        { 1, 0, 1, 1 },
    },
}

return CTF_CONSTANTS;
