---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-22 11:09 p.m.
---
local require = _G.require;
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');

local RETARGET_ONEOF_TAGS = { CTF_TEAM_CONSTANTS.TEAM_MINION_TAG, CTF_TEAM_CONSTANTS.TEAM_PLAYER_TAG, CTF_TEAM_CONSTANTS.TEAM_MINION_SPAWNER_TAG };

local findEnemy = function(inst, radius, teamTag)
    return FindEntity(inst, radius, nil, { "_combat", "_health" }, { teamTag, 'INLIMBO' }, RETARGET_ONEOF_TAGS);
end

return {
    findEnemy = findEnemy,
}
