---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-05 2:34 p.m.
---

local CTFTeamMarker = Class(function(self, owner)
    local anchor = SpawnPrefab('ctf_team_marker');
    local marker = SpawnPrefab('ctf_team_marker');

    anchor.Transform:SetPosition(0, -0.05, 0);
    --anchor.AnimState:SetScale(0.5, 0.5);
    anchor.entity:SetParent(owner.entity);
    anchor.entity:Hide();

    marker.AnimState:PlayAnimation('health');
    marker.AnimState:SetDeltaTimeMultiplier(0);
    marker.AnimState:SetTime(0);
    marker.AnimState:SetScale(-1, 1);

    marker.Follower:FollowSymbol(anchor.GUID, 'assets', 0, 0, 0);

    anchor.entity:SetPristine();
    marker.entity:SetPristine();

    if owner.components and owner.components.health then
        owner:ListenForEvent('healthdelta', function(_, data)
            if owner:HasTag('playerghost') then
                self:setPercent(0);
            else
                self:setPercent(data.newpercent);
            end
        end)
    end

    self.anchor = anchor;
    self.marker = marker;
    self.owner = owner;
    self.percent = 1;
end);

function CTFTeamMarker:setPercent(percent)
    self.percent = percent;
    self.marker.AnimState:SetTime(3.61 * (1 - percent));
end

function CTFTeamMarker:setHue(r, g, b, a)
    self.marker.AnimState:SetMultColour(r, g, b, a);
end

return CTFTeamMarker;
