---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 11:33 a.m.
---

local Health = require('components/health');
local SourceModifierList = require("util/sourcemodifierlist")
local CTFClassPatcher = use('scripts/tools/CTFClassPatcher');

CTFClassPatcher(Health, function(self, ctor, inst)
    ctor(self, inst);
    self.rawDamageModifiers = SourceModifierList(inst);
end);

function Health:DoRawDamage(damage, cause, afflicter, overTime)
    damage = damage * self.rawDamageModifiers:Get();
    self:DoDelta(-damage, overTime, cause, true, afflicter, true);
end
