---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-15 11:33 a.m.
---

local require = _G.require;
local CTF_CONSTANTS = require('teams/CTFTeamConstants');

AddPrefabPostInit('waxwell', function(inst)
    if inst.components then
        if inst.components.sanity then
            inst.components.sanity.AddSanityPenalty = function(_, _)  end;
        end

        if inst.components.petleash then
            local OldOnSpawnFn = inst.components.petleash.onspawnfn;
            inst.components.petleash.onspawnfn = function(f_inst, pet)
                OldOnSpawnFn(f_inst, pet);
                if f_inst:HasTag(CTF_CONSTANTS.TEAM_PLAYER_TAG) then
                    local team = CTFTeamManager:getPlayerTeam(f_inst);
                    if team ~= nil then
                        team:registerObject(pet, nil);
                    end
                end
            end
        end
    end
end);
