---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 5:32 p.m.
---

local CTF_CHARACTER_CONSTANTS = use('scripts/constants/CTFCharacterConstants');
local CTFInit = use('scripts/tools/CTFInit');

local master_post_init = function(inst)
    -- disable damage absorption
    inst.components.health:SetAbsorptionAmount(0.0);
end

CTFInit:Character('wathgrithr', nil, master_post_init);
