---bishop.lua
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-14 6:50 p.m.
---

local WEBBER_SPIDER_ABSORPTION = 0.45;

AddPrefabPostInit('webber', function(inst)
    if inst.components and inst.components.health then
        local OldDoDelta = inst.components.health.DoDelta;
        inst.components.health.DoDelta = function (self, amount, overtime, cause, ignore_invincible, afflicter, ignore_absorb)
            if afflicter and afflicter:HasTag('spider') then
                amount = amount * (1.0 - WEBBER_SPIDER_ABSORPTION);
            end
            return OldDoDelta(self, amount, overtime, cause, ignore_invincible, afflicter, ignore_absorb);
        end
    end
end);
