---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-14 9:41 a.m.
---
local require = _G.require;
local Armor = require('components/armor');

local WES_MAX_HEALTH = 75;
local WES_MAX_HUNGER = 75;
local WES_MAX_SANITY = 75;
local WES_UNARMED_DAMAGE = 25;
local WES_DAMAGE_MULTIPLIER = 1.55;
local WES_ARMOR_MULTIPLIER = 0.3;

local OldArmorGetAbsorption = Armor.GetAbsorption;
Armor.GetAbsorption = function(self, attacker, weapon)
    local absorption = OldArmorGetAbsorption(self, attacker, weapon);
    if
        absorption and
        self.inst.components.inventoryitem and
        self.inst.components.inventoryitem.owner and
        self.inst.components.inventoryitem.owner.prefab == 'wes'
    then
        absorption = absorption * WES_ARMOR_MULTIPLIER;
    end
    return absorption;
end

AddPrefabPostInit('wes', function(inst)
    if inst.components then
        if inst.components.health then
            inst.components.health:SetMaxHealth(WES_MAX_HEALTH);
        end

        if inst.components.hunger then
            inst.components.hunger:SetMax(WES_MAX_HUNGER);
        end

        if inst.components.sanity then
            inst.components.sanity:SetMax(WES_MAX_SANITY);
        end

        if inst.components.combat then
            inst.components.combat:SetDefaultDamage(WES_UNARMED_DAMAGE);
            inst.components.combat.damagemultiplier = WES_DAMAGE_MULTIPLIER;
        end
    end
end);
