---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-14 11:40 p.m.
---
local require = _G.require;
local CTF_CONSTANTS = require('teams/CTFTeamConstants');

local WICKERBOTTOM_BOOK_HEAL = 45;
local WICKERBOTTOM_BOOK_HUNGER = 35;

AddPrefabPostInit('book_silviculture', function(inst)
    if inst.components and inst.components.book then
        inst.components.book.onread = function(f_inst, reader)
            if reader:HasTag(CTF_CONSTANTS.TEAM_PLAYER_TAG) and reader.data and reader.data.ctf_team_tag then
                local teamTag = reader.data.ctf_team_tag;
                local x, y, z = reader.Transform:GetWorldPosition();
                local range = 30;
                local ents = TheSim:FindEntities(x, y, z, range, { teamTag });
                for _, v in ipairs(ents) do
                    if v.components then
                        if v.components.health then
                            v.components.health:DoDelta(WICKERBOTTOM_BOOK_HEAL, nil, f_inst.prefab);
                        end

                        if v.components.hunger then
                            v.components.hunger:DoDelta(WICKERBOTTOM_BOOK_HUNGER);
                        end
                    end
                end
            end
            return true;
        end
    end
end);
