---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-21 10:53 p.m.
---

local CTF_CHARACTER_CONSTANTS = use('scripts/constants/CTFCharacterConstants');
local CTFCharacterPostInit = use('scripts/CTFCharacterPostInit');

CTFCharacterPostInit('willow', function(inst, ctfPlayer)
    if TheWorld.ismastersim then
        inst:AddComponent('cooldown');

        inst.components.cooldown.cooldown_duration = CTF_CHARACTER_CONSTANTS.WILLOW.LIGHTER_FIRE_BLAST_COOLDOWN;

        inst.components.cooldown.startchargingfn = function()
            ctfPlayer.net.cooldown_charged.var:set(false);
            ctfPlayer.net.cooldown_time.var:set(inst.components.cooldown:GetTimeToCharged());
        end

        inst.components.cooldown.onchargedfn = function()
            ctfPlayer.net.cooldown_charged.var:set(true);
            ctfPlayer.net.cooldown_time.var:set(0);
        end

        inst.components.cooldown:StartCharging();
    end
end);

AddStategraphState('wilson', State {
    name = 'ctf_fire_blast',
    tags = { 'doing', 'busy' },

    onenter = function(inst)
        inst.components.locomotor:Stop();
        inst.AnimState:PlayAnimation('unsaddle_pre');
        inst.AnimState:PushAnimation('unsaddle', false);

        inst.sg.statemem.action = inst.bufferedaction;
        inst.sg:SetTimeout(21 * FRAMES);
    end,

    timeline =
    {
        TimeEvent(13 * FRAMES, function(inst)
            inst.sg:RemoveStateTag('busy');
        end),
        
        TimeEvent(10 * FRAMES, function(inst)
            inst:PerformBufferedAction();
        end),
    },

    ontimeout = function(inst)
        --pickup_pst should still be playing
        inst.sg:GoToState('idle', true);
    end,

    onexit = function(inst)
        if inst.bufferedaction == inst.sg.statemem.action then
            inst:ClearBufferedAction();
        end
    end,
});

local TIMEOUT = 2;
AddStategraphState('wilson_client', State {
    name = 'ctf_fire_blast',
    tags = { 'doing', 'busy' },

    onenter = function(inst)
        inst.components.locomotor:Stop();
        inst.AnimState:PlayAnimation('unsaddle_pre');
        inst.AnimState:PushAnimation('unsaddle_lag', false);

        inst:PerformPreviewBufferedAction();
        inst.sg:SetTimeout(TIMEOUT);
    end,

    timeline =
    {
        TimeEvent(13 * FRAMES, function(inst)
            inst.sg:RemoveStateTag('busy');
        end),
    },

    onupdate = function(inst)
        if inst:HasTag('doing') then
            if inst.entity:FlattenMovementPrediction() then
                inst.sg:GoToState('idle', 'noanim');
            end
        elseif inst.bufferedaction == nil then
            inst.AnimState:PlayAnimation('unsaddle');
            inst.sg:GoToState('idle', true);
        end
    end,

    ontimeout = function(inst)
        inst:ClearBufferedAction();
        inst.AnimState:PlayAnimation('unsaddle');
        inst.sg:GoToState('idle', true);
    end,
});
