---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-17 10:46 p.m.
---

local require = _G.require;
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');

local WILSON_BEARD_DAMAGE_INCREASE = 0.3;
local WILSON_BEARD_DAMAGE_REDUCTION = 0.25;
local WILSON_BEARD_MIN_BOUNTY = 10;
local WILSON_BEARD_MAX_BOUNTY = 60;

AddPrefabPostInit('wilson', function(inst)
    if inst.userid and inst.components and inst.components.beard then
        local beardCallbacks = {};
        for i = 1, 99 do
            local cb = inst.components.beard.callbacks[i];
            if cb then
                inst.components.beard.callbacks[i] = nil;
                table.insert(beardCallbacks, cb);
            end
        end

        inst.ctfPlayerHandler = function(_, ctfPlayer)
            if ctfPlayer and ctfPlayer:getUserID() == inst.userid then

                TheWorld:RemoveEventCallback(CTF_TEAM_CONSTANTS.PLAYER_REGISTERED_EVENT, inst.ctfPlayerHandler);

                inst.ctfBeardLevel = 0;
                inst.ctfBountyOffset = ctfPlayer:getBounty();

                ctfPlayer.net:ListenForEvent(ctfPlayer.net.bounty.event, function(net)
                    local bounty = net.bounty.var:value() - inst.ctfBountyOffset;
                    local normalizedBounty = math.max(WILSON_BEARD_MIN_BOUNTY, math.min(WILSON_BEARD_MAX_BOUNTY, bounty));
                    local bountyProgress = (normalizedBounty - WILSON_BEARD_MIN_BOUNTY) / (WILSON_BEARD_MAX_BOUNTY - WILSON_BEARD_MIN_BOUNTY);

                    local damageMultiplier = 1.0 + WILSON_BEARD_DAMAGE_INCREASE * bountyProgress;
                    inst.components.combat.damagemultiplier = damageMultiplier;

                    local damageReduction = WILSON_BEARD_DAMAGE_REDUCTION * bountyProgress;
                    inst.components.health:SetAbsorptionAmount(damageReduction);

                    if #beardCallbacks > 0 then
                        local beardIndex = math.floor(#beardCallbacks * bountyProgress);
                        if beardIndex ~= inst.ctfBeardLevel then
                            inst.ctfBeardLevel = beardIndex;
                            if inst.ctfBeardLevel == 0 then
                                inst.components.beard:Reset();
                            else
                                beardCallbacks[inst.ctfBeardLevel](inst, inst.components.beard.skinname);
                            end
                        end
                    end
                end);

                inst:ListenForEvent('ms_respawnedfromghost', function()
                    inst.ctfBountyOffset = ctfPlayer:getBounty();
                end);
            end
        end
        TheWorld:ListenForEvent(CTF_TEAM_CONSTANTS.PLAYER_REGISTERED_EVENT, inst.ctfPlayerHandler);
    end
end);
