---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-15 6:04 p.m.
---
local require = GLOBAL.require;
local CTFTeamCombat = require('teams/CTFTeamCombat');

TUNING.WINONA_CATAPULT_MIN_RANGE = 0;

AddPrefabPostInit('winona_catapult', function(inst)
    if inst.components then
        if inst.components.combat then
            local OldRetargetFunction = inst.components.combat.targetfn;
            inst.components.combat:SetRetargetFunction(0.5, function(f_inst)
                if f_inst.data and f_inst.data.ctf_team_tag then
                    local target = f_inst.components.combat.target
                    return CTFTeamCombat.findEnemy(f_inst, TUNING.WINONA_CATAPULT_MAX_RANGE, f_inst.data.ctf_team_tag), target ~= nil;
                end
                return OldRetargetFunction(f_inst);
            end);
        end
    end
end);

AddPrefabPostInit('winona_catapult_projectile', function(inst)
    if inst.components then
        if inst.components.complexprojectile then
            inst.components.complexprojectile:SetOnLaunch(function(f_inst)
                local team = CTFTeamManager:getObjectTeam(f_inst.components.complexprojectile.attacker);
                if team ~= nil then
                    team:registerObject(f_inst, nil);
                end
            end);
        end
    end
end);
