---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-15 6:04 p.m.
---
local require = GLOBAL.require;
local CTFTeamCombat = require('teams/CTFTeamCombat');

local WINONA_MAX_CATAPULTS = 3;

TUNING.WINONA_CATAPULT_MIN_RANGE = 0;
TUNING.WINONA_CATAPULT_HEALTH = 250;
TUNING.WINONA_CATAPULT_DAMAGE = 35;

AddPrefabPostInit('winona_catapult', function(inst)
    if inst.components then
        if inst.components.combat then
            local OldRetargetFunction = inst.components.combat.targetfn;
            inst.components.combat:SetRetargetFunction(0.5, function(f_inst)
                if f_inst.data and f_inst.data.ctf_team_tag then
                    local target = f_inst.components.combat.target
                    return CTFTeamCombat.findEnemy(f_inst, TUNING.WINONA_CATAPULT_MAX_RANGE, f_inst.data.ctf_team_tag), target ~= nil;
                end
                return OldRetargetFunction(f_inst);
            end);
        end
    end
end);

AddPrefabPostInit('winona_catapult_projectile', function(inst)
    if inst.components then
        if inst.components.complexprojectile then
            inst.components.complexprojectile:SetOnLaunch(function(f_inst)
                local team = CTFTeamManager:getObjectTeam(f_inst.components.complexprojectile.attacker);
                if team ~= nil then
                    team:registerObject(f_inst, nil);
                end
            end);
        end
    end
end);

AddPrefabPostInit('winona', function(inst)
    if inst.components and inst.components.builder then
        local winona_active_catapults = 0;
        local OldCanBuild = inst.components.builder.CanBuild;
        inst.components.builder.CanBuild = function(self, recname)
            local result = OldCanBuild(self, recname);
            if result and recname == 'winona_catapult' and winona_active_catapults >= WINONA_MAX_CATAPULTS then
                return false;
            end
            return result;
        end

        local OldOnBuild = inst.components.builder.onBuild;
        inst.components.builder.onBuild = function(f_inst, prod)
            if prod and prod.prefab == 'winona_catapult' then
                winona_active_catapults = winona_active_catapults + 1;

                if prod.inst then
                    prod.inst:ListenForEvent("death", function()
                        winona_active_catapults = winona_active_catapults - 1;
                    end);
                end
            end

            if OldOnBuild then
                OldOnBuild(f_inst, prod);
            end
        end
    end
end);

