---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-14 12:20 a.m.
---

AddPrefabPostInit('wolfgang', function(inst)
    local OldApplyScale = inst.ApplyScale;
    inst.ApplyScale = function(f_inst, source, scale)
        OldApplyScale(f_inst, source, scale);
        if f_inst.components and f_inst.components.locomotor then
            if scale > 1 then
                f_inst.components.locomotor:SetExternalSpeedMultiplier(f_inst, "ctf_anti_mightiness", 1 / scale);
            else
                f_inst.components.locomotor:RemoveExternalSpeedMultiplier(f_inst, "ctf_anti_mightiness");
            end
        end
    end
end);
