---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-11 10:34 a.m.
---

AddPrefabPostInit('woodie', function(inst)
    if inst.components and inst.components.tackler then
        -- thanks to KoreanWaffles#1782
        inst.components.tackler:AddWorkAction(ACTIONS.HAMMER, 0);
    end
end);
