---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-07 10:28 p.m.
---

local require = _G.require;
local wortox_soul_common = require("prefabs/wortox_soul_common");
wortox_soul_common.HasSoul = function() return false  end;

AddPrefabPostInit('wortox', function(inst)
    inst.nosoultask = true;
end);
