---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-16 9:32 p.m.
---

local function ctf_ondeath(inst)
    if inst.level > 0 then
        local dropgears = math.ceil(inst.level / 2);
        if dropgears > 0 then
            local team = CTFTeamManager:getPlayerTeam(inst.userid);
            for i = 1, dropgears do
                local gear = SpawnPrefab("gears");
                if gear ~= nil then
                    if team then
                        team:registerObject(gear, nil);
                    end

                    local x, y, z = inst.Transform:GetWorldPosition();
                    if gear.Physics ~= nil then
                        local speed = 2 + math.random();
                        local angle = math.random() * 2 * PI;
                        gear.Transform:SetPosition(x, y + 1, z);
                        gear.Physics:SetVel(speed * math.cos(angle), speed * 3, speed * math.sin(angle));
                    else
                        gear.Transform:SetPosition(x, y, z);
                    end
                    if gear.components.propagator ~= nil then
                        gear.components.propagator:Delay(5);
                    end
                end
            end
        end
        inst:OnPreLoad({ level = 0 });
    end
end

AddPrefabPostInit('wx78', function(inst)
    if TheWorld.ismastersim then
        if inst.event_listening.death and inst.event_listening.death[inst] then
            for i, fn in ipairs(inst.event_listening.death[inst]) do
                local info = debug.getinfo(fn, 'S');
                if info and info.source and info.source:match('prefabs[/\\]wx78.lua$') then
                    inst:RemoveEventCallback('death', fn);
                    inst:ListenForEvent('death', ctf_ondeath);
                    break
                end
            end
        end
    end
end);
