---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-22 10:20 a.m.
---

--- TRANSLATED BY: JesterOK
--- DISCORD: https://discord.gg/E9D8bTp

local CTF_STRINGS = {
    WELCOME = {
        TITLE = 'Добро пожаловать в Захват флага!',
        TEXT = 'В этой игре участвуют две команды, каждая имеет свой оттенок.\nЦель игры состоит в том, чтобы принести "Свиной мешок" противника к вашей базе.\nИспользуйте золото для изготовления оружия, доспехов и еды.\nВы можете получить золото, победив врагов.\nНекоторые существа дружелюбные, а некоторые нет, в любом случае из них всех выпадает золото.\nУдачи!',

        OK = 'OK',

        DISCORD = 'Discord',
        DISCORD_LINK = 'https://discord.gg/E9D8bTp',

        VIDEO = 'Video Tutorial',
        VIDEO_LINK = 'https://www.youtube.com/embed/_LN5mRUN6cE?autoplay=1',
    },

    CHAT_ALL = '[ВСЕ]',
    CHAT_TEAM = '[КОМАНДА]',

    CHAT_ALL_SHORT = '[В]',
    CHAT_TEAM_SHORT = '[К]',

    CHAT_TEAM_DELIMITER = '\n',
}

return CTF_STRINGS;
