---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-21 1:35 p.m.
---

local CTF_ANIM_CONSTANTS = {
    spider = {
        [1] = 'ctf_spider_team1',
    },
}

return CTF_ANIM_CONSTANTS;
