---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-08 9:59 p.m.
---

local CTF_CHARACTER_CONSTANTS = {
    WENDY = {
        ABI_REGEN_PERIOD = 1,
        ABI_REGEN_AMOUNT = 3;
    }
}

return CTF_CHARACTER_CONSTANTS;
