---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-08 9:59 p.m.
---

local CTF_CHARACTER_CONSTANTS = {
    WENDY = {
        ABI_REGEN_PERIOD = 1,
        ABI_REGEN_AMOUNT = 3;
    },

    WILLOW = {
        LIGHTER_ATTACK_PERIOD = 0.55,
        LIGHTER_ATTACK_RANGE_MIN = 3,
        LIGHTER_ATTACK_RANGE_MAX = 4,
        LIGHTER_HIT_DAMAGE = 23,

        LIGHTER_SMOLDER_TICK_TIME = 1.0,
        LIGHTER_SMOLDER_TICK_COUNT = 3,
        LIGHTER_SMOLDER_TICK_DAMAGE = 1,
        LIGHTER_MAX_SMOLDER_STACKS = 5,

        LIGHTER_FIRE_BLAST_USES = 5,
        LIGHTER_FIRE_BLAST_COOLDOWN = 5,
        LIGHTER_FIRE_BLAST_DISTANCE = 12,
        LIGHTER_FIRE_BLAST_DAMAGE = 30,
        LIGHTER_FIRE_BLAST_FIRE_TICK_TIME = 0.6,
        LIGHTER_FIRE_BLAST_FIRE_TICK_COUNT = 5,
        LIGHTER_FIRE_BLAST_FIRE_TICK_DAMAGE = 3,
        LIGHTER_FIRE_BLAST_FIRE_SMOLDER_STACK_DAMAGE = 1,
    },

    WARLY = {
        FOOD = {
            glowberrymousse = {
                health = 5,
                hunger = 20,
            },
        
            potatosouffle = {
                health = 35,
                hunger = 60,
            },
        
            monstertartare = {
                health = -5,
                hunger = 30,
            },
        
            freshfruitcrepes = {
                health = 80,
                hunger = 125,
            },
        
            moqueca = {
                health = 60,
                hunger = 70,
            },
        
            bonesoup = {
                health = 30,
                hunger = 100,
            },
        }
    }
}

return CTF_CHARACTER_CONSTANTS;
