---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-08 9:59 p.m.
---

local CTF_CHARACTER_CONSTANTS = {
    WENDY = {
        ABI_REGEN_PERIOD = 1,
        ABI_REGEN_AMOUNT = 3;
    },

    WILLOW = {
        LIGHTER_ATTACK_PERIOD = 0.7,
        LIGHTER_ATTACK_RANGE_MIN = 4,
        LIGHTER_ATTACK_RANGE_MAX = 5,
        LIGHTER_HIT_DAMAGE = 20,
        LIGHTER_SMOLDER_TICK_TIME = 0.75,
        LIGHTER_SMOLDER_TICK_COUNT = 5,
        LIGHTER_SMOLDER_TICK_DAMAGE = 2,
        LIGHTER_MAX_SMOLDER_STACKS = 5;
    }
}

return CTF_CHARACTER_CONSTANTS;
