---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-22 1:09 p.m.
---

local CTF_LANGUAGE_CODE = GetModConfigData('CTF_LANGUAGE');

if not CTF_LANGUAGE_CODE then
    -- check for known mods
    if KnownModIndex:IsModEnabled('workshop-2286791724') then -- [Beta]Russification Pack for DST
        CTF_LANGUAGE_CODE = 'ru';
    else
        local locale = GetCurrentLocale and GetCurrentLocale() or nil;
        CTF_LANGUAGE_CODE = locale and locale.code or 'en';
    end
end

return CTF_LANGUAGE_CODE;

