---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-02 3:37 p.m.
---

local CTF_MISC_CONSTANTS = {
    DISABLED_CHARACTERS = {
        'wurt',
    },

    SLEEP_HUNGER_PER_TICK = -2,
    SLEEP_HEALTH_PER_TICK = 3,
}

return CTF_MISC_CONSTANTS;
