---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-02 3:37 p.m.
---

local CTF_MISC_CONSTANTS = {
    DISABLED_CHARACTERS = {
        'wilson',
        'willow',
        'wendy',
        'wurt',
    }
}

return CTF_MISC_CONSTANTS;
