---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-27 7:56 p.m.
---

local CTF_RUSH_CONSTANTS = {
    DEFAULT_LOOT = {
        gold = 5,
    },
    BOSS_LOOT_MULTIPLIER = 3,
}

return CTF_RUSH_CONSTANTS;
