---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-21 5:39 p.m.
---

local CTF_STRINGS = {
    CHAT_ALL = '[ALL]',
    CHAT_TEAM = '[TEAM]',

    CHAT_ALL_SHORT = '[A]',
    CHAT_TEAM_SHORT = '[T]',

    CHAT_TEAM_DELIMITER = '\n',
}

return CTF_STRINGS;
