---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-21 5:39 p.m.
---

local require = _G.require;
local CTF_STRINGS = use('scripts/constants/locales/CTFStrings_en');
local CTF_LANGUAGE_CODE = use('scripts/constants/CTFLanguageCode');

local function deepCopyStrings(source, target)
    for k, v in pairs(source) do
        if type(v) == 'string' then
            target[k] = v;
        elseif target[k] and type(target[k]) == 'table' then
            deepCopyStrings(v, target[k]);
        end
    end
end

if CTF_LANGUAGE_CODE ~= 'en' then
    local status, CTF_STRINGS_LOCALIZED = pcall(require, 'constants/locales/CTFStrings_' .. CTF_LANGUAGE_CODE);
    if status == true then
        deepCopyStrings(CTF_STRINGS_LOCALIZED, CTF_STRINGS);
    end
end

return CTF_STRINGS;
