---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-09 5:29 p.m.
---

local function cast_noop() return true end;

local AOESpell = Class(function(self, inst)
    self.inst = inst;
    self.str = nil;
    self.distance = 8; -- this is the default
    self.can_cast = cast_noop;
    self.cast_spell = cast_noop;
    self.expected_doer = 'nobody';
    self.expected_item = 'none';
end);

function AOESpell:CanCast(doer, pos)
    return self.can_cast(doer, pos);
end

function AOESpell:CastSpell(doer, pos)
    return self.cast_spell(doer, pos);
end

return AOESpell;
