---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-02 7:56 p.m.
---
local require = _G.require;
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');

local CTFTeamMarker = Class(function(self, inst)
    --self.player = inst.entity:GetParent();
    self.marker = inst:SpawnChild('ctf_team_marker');
end);

function CTFTeamMarker:SetTeam(teamID)
    self.marker.Label:SetText('[T' .. teamID .. ']');
    self.marker.Label:SetColour(unpack(CTF_TEAM_CONSTANTS.TEAM_COLORS[math.min(teamID, 5)]));
end

return CTFTeamMarker;
