---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-20 6:14 p.m.
---

local require = _G.require;
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');

local ItemTypeRestrictions = Class(function(self, inst)
    self.player = inst.entity:GetParent();
    self.ctfTeamTag = 'none';
    self.noCtfTeamTag = 'none';
    self.inst = inst;
end);

function ItemTypeRestrictions:IsAllowed(target)
    if target:HasTag(CTF_TEAM_CONSTANTS.ITEM_LOCKED_TAG) then
        return false
    elseif target:HasTag(CTF_TEAM_CONSTANTS.TEAM_ITEM_TAG) then
        if target:HasTag(self.ctfTeamTag) then
            return true;
        else
            return false
        end
    elseif target:HasTag(self.noCtfTeamTag) then
        return false;
    end
    return true;
end

return ItemTypeRestrictions;

