---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-31 8:15 p.m.
---

local PVPWeapon = Class(function(self, inst)
    self.inst = inst;
    -- weapons can stun anything by default
    self.canStunFn = nil;
end);

function PVPWeapon:canStun(target)
    if self.canStunFn then
        return self.canStunFn(self.inst, target);
    end
    return true;
end

return PVPWeapon;
