---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-21 11:46 a.m.
---

local Widget = require('widgets/widget');
local Image = require('widgets/image');
local Text = require('widgets/text');

local CTFPlayerStats = Class(Widget, function(self)
    Widget._ctor(self, 'ctf_player_stats');

    self.killsIcon = self:AddChild(Image('images/ctf_crafting_tabs.xml', 'ctf_tab_weapons.tex'));
    self.killsIcon:SetScale(0.32, 0.32);
    self.killsIcon:SetPosition(0, 3, 0);

    self.kills = self:AddChild(Text(UIFONT, 35, ''));
    self.kills:SetPosition(38, 0, 0);
    self.kills:SetHAlign(ANCHOR_LEFT);

    self.deathsIcon = self:AddChild(Image('images/ctf_crafting_tabs.xml', 'ctf_tab_deaths.tex'));
    self.deathsIcon:SetScale(0.32, 0.32);
    self.deathsIcon:SetPosition(68, 3, 0);

    self.deaths = self:AddChild(Text(UIFONT, 35, ''));
    self.deaths:SetPosition(106, 0, 0);
    self.deaths:SetHAlign(ANCHOR_LEFT);

    self.assistsIcon = self:AddChild(Image('images/ctf_crafting_tabs.xml', 'ctf_tab_assists.tex'));
    self.assistsIcon:SetScale(0.32, 0.32);
    self.assistsIcon:SetPosition(136, 3, 0);

    self.assists = self:AddChild(Text(UIFONT, 35, ''));
    self.assists:SetPosition(174, 0, 0);
    self.assists:SetHAlign(ANCHOR_LEFT);

    self.bountyIcon = self:AddChild(Image('images/ctf_crafting_tabs.xml', 'ctf_tab_bounty.tex'));
    self.bountyIcon:SetScale(0.5, 0.5);
    self.bountyIcon:SetPosition(204, 3, 0);

    self.bounty = self:AddChild(Text(UIFONT, 35, ''));
    self.bounty:SetPosition(250, 0, 0);
    self.bounty:SetHAlign(ANCHOR_LEFT);

    self.userid = nil;
    self.ctfPlayer = nil;

    self.updateStatsHandler = function()
        self:updateStats();
    end

    self:hideStats();
end);

function CTFPlayerStats:hideStats()
    self.killsIcon:Hide();
    self.kills:Hide();
    self.deathsIcon:Hide();
    self.deaths:Hide();
    self.assistsIcon:Hide();
    self.assists:Hide();
    self.bountyIcon:Hide();
    self.bounty:Hide();
end

function CTFPlayerStats:showStats()
    self.killsIcon:Show();
    self.kills:Show();
    self.deathsIcon:Show();
    self.deaths:Show();
    self.assistsIcon:Show();
    self.assists:Show();
    self.bountyIcon:Show();
    self.bounty:Show();
end

function CTFPlayerStats:setUser(userid)
    local ctfPlayer = userid and CTFTeamManager:getCTFPlayer(userid) or nil;
    if ctfPlayer ~= self.ctfPlayer then
        if self.ctfPlayer then
            self:unregisterStatsEvents(self.ctfPlayer);
        end
        self.userid = userid;
        self.ctfPlayer = ctfPlayer;

        if self.ctfPlayer then
            self:showStats();
            self:updateStats();
            self:registerStatsEvents(self.ctfPlayer);
        else
            self:hideStats();
        end
    end
end

function CTFPlayerStats:updateStats()
    if self.ctfPlayer then
        self.kills:SetString('' .. self.ctfPlayer:getKills());
        self.deaths:SetString('' .. self.ctfPlayer:getDeaths());
        self.assists:SetString('' .. self.ctfPlayer:getAssists());
        self.bounty:SetString('' .. self.ctfPlayer:getBounty());
    end
end

function CTFPlayerStats:registerStatsEvents(ctfPlayer)
    if ctfPlayer then
        ctfPlayer.net:ListenForEvent(ctfPlayer.net.kills.event, self.updateStatsHandler);
        ctfPlayer.net:ListenForEvent(ctfPlayer.net.deaths.event, self.updateStatsHandler);
        ctfPlayer.net:ListenForEvent(ctfPlayer.net.assists.event, self.updateStatsHandler);
        ctfPlayer.net:ListenForEvent(ctfPlayer.net.bounty.event, self.updateStatsHandler);
    end
end

function CTFPlayerStats:unregisterStatsEvents(ctfPlayer)
    if ctfPlayer then
        ctfPlayer.net:RemoveEventCallback(ctfPlayer.net.kills.event, self.updateStatsHandler);
        ctfPlayer.net:RemoveEventCallback(ctfPlayer.net.deaths.event, self.updateStatsHandler);
        ctfPlayer.net:RemoveEventCallback(ctfPlayer.net.assists.event, self.updateStatsHandler);
        ctfPlayer.net:RemoveEventCallback(ctfPlayer.net.bounty.event, self.updateStatsHandler);
    end
end

function CTFPlayerStats:Kill()
    if self.ctfPlayer then
        self:unregisterStatsEvents(self.ctfPlayer);
    end
    CTFPlayerStats._base.Kill(self)
end

return CTFPlayerStats;
