---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-27 8:47 p.m.
---

local CTFInit = require('tools/CTFInit');
local DragonflyBrain = require('brains/dragonflybrain');

local upvalues = CTFInit:RetrieveUpvalues(DragonflyBrain.OnStart);

if upvalues['ShouldResetFight'] then
    local up = upvalues['ShouldResetFight'];
    debug.setupvalue(DragonflyBrain.OnStart, up.i, function() return false end);
end

if upvalues['ShouldRetryReset'] then
    local up = upvalues['ShouldRetryReset'];
    debug.setupvalue(DragonflyBrain.OnStart, up.i, function() return false end);
end
