---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-20 12:01 p.m.
---

local CTFBossFightInfo = {
    {
        initialDelay = 10, -- in seconds
        nextWaveDelay = 3, -- in seconds
        playerLostCoolDown = 10, -- in seconds
        playerWonCoolDown = 10, -- in seconds
        islandRadius = 80, -- in game units
        centerSpawner = 'middle01',
        waves = {
            -- wave 1
            {
                mobs = {
                    middle01 = {
                        { prefab = 'frog', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 3, },
                }
            },

            -- wave 2
            {
                mobs = {
                    middle01 = {
                        { prefab = 'hound', count = 1 },
                    },
                    topright01 = {
                        { prefab = 'firehound', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'icehound', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'mutatedhound', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'mutatedhound', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 5 },
                    { prefab = 'spear', count = 1, },
                }
            },
            -- wave 3
            {
                mobs = {
                    topright01 = {
                        { prefab = 'walrus', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'little_walrus', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'icehound', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'icehound', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                    { prefab = 'spear', count = 1, },
                }
            },

            -- wave 4
            {
                mobs = {
                    middle01 = {
                        { prefab = 'penguin', count = 1 },
                    },
                    topright01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                    { prefab = 'spear', count = 1, },
                }
            },
            
            -- wave 5
            {
                mobs = {
                    middle01 = {
                        { prefab = 'bishop', count = 1 },
                    },
                    topright01 = {
                        { prefab = 'knight', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'knight', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'knight', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'knight', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                    { prefab = 'spear', count = 1, },
                }
            },
        }
    },
}

return CTFBossFightInfo;
