---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-20 12:01 p.m.
---

local CTFBossFightInfo = {
    {
        name = 'Dragonfly',
        initialDelay = 30, -- in seconds
        nextWaveDelay = 3, -- in seconds
        playerLostCoolDown = 240, -- in seconds
        playerWonCoolDown = 1440, -- in seconds
        islandRadius = 40, -- in game units
        centerSpawner = 'middle01',
        waves = {

            -- wave 1
            {
                mobs = {
                    middle01 = {
                        { prefab = 'frog', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 3, },
                }
            },

            -- wave 2
            {
                mobs = {
                    middle01 = {
                        { prefab = 'penguin', count = 1 },
                    },
                    topright01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'mutated_penguin', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 5 },
                }
            },
            
            -- wave 3
            {
                mobs = {
                    topright01 = {
                        { prefab = 'walrus', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'little_walrus', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'icehound', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'icehound', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                }
            },

            -- wave 4
            {
                mobs = {
                    middle01 = {
                        { prefab = 'hound', count = 1 },
                    },
                    topright01 = {
                        { prefab = 'firehound', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'firehound', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'mutatedhound', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'mutatedhound', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 15 },
                }
            },
            
            -- wave 5
            {
                mobs = {
                    middle01 = {
                        { prefab = 'bishop', count = 1 },
                    },
                    topright01 = {
                        { prefab = 'rook', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'rook', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'knight', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'knight', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                    { prefab = 'spear', count = 1, },
                }
            },

            -- wave 6
            {
                mobs = {
                    middle01 = {
                        { prefab = 'spiderqueen', count = 1 },
                    },
                    topright01 = {
                        { prefab = 'spider_hider', count = 1 },
                    },
                    bottomleft01 = {
                        { prefab = 'spider_hider', count = 1 },
                    },
                    topleft01 = {
                        { prefab = 'spider_hider', count = 1 },
                    },
                    bottomright01 = {
                        { prefab = 'spider_hider', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                    { prefab = 'ruins_bat', count = 1, },
                }
            },
            
            -- wave 7
            {
                mobs = {
                    middle01 = {
                        { prefab = 'deerclops', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                    { prefab = 'greenamulet', count = 1, },
                }
            },
            
            -- wave 9
            {
                mobs = {
                    middle01 = {
                        { prefab = 'dragonfly', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                    { prefab = 'cane', count = 1, },
                }
            },
            
            -- wave 10
            {
                mobs = {
                    middle01 = {
                        { prefab = 'rabbit', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 50 },
                    { prefab = 'tallbirdegg', count = 3, },
                    { prefab = 'nightstick_blueprint', count = 1, },
                    { prefab = 'waterballoon', count = 10, },
                }
            },
        }
    },
    {
        name = 'Klaus',
        initialDelay = 30, -- in seconds
        nextWaveDelay = 3, -- in seconds
        playerLostCoolDown = 240, -- in seconds
        playerWonCoolDown = 1440, -- in seconds
        islandRadius = 40, -- in game units
        centerSpawner = 'middle02',
        waves = {

            -- wave 1
            {
                mobs = {
                    middle02 = {
                        { prefab = 'bat', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 3, },
                }
            },

            -- wave 2
            {
                mobs = {
                    topright02 = {
                        { prefab = 'tallbird', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 5 },
                }
            },

            -- wave 3
            {
                mobs = {
                    middle02 = {
                        { prefab = 'koalefant_winter', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 10 },
                }
            },

            -- wave 4
            {
                mobs = {
                    bottomleft02 = {
                        { prefab = 'spat', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 20 },
                }
            },

            -- wave 5
            {
                mobs = {
                    middle02 = {
                        { prefab = 'warg', count = 1 },
                    },
                    topright02 = {
                        { prefab = 'hound', count = 1 },
                    },
                    bottomleft02 = {
                        { prefab = 'hound', count = 1 },
                    },
                    topleft02 = {
                        { prefab = 'hound', count = 1 },
                    },
                    bottomright02 = {
                        { prefab = 'hound', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 15 },
                    { prefab = 'batbat', count = 1, },
                }
            },

            -- wave 6
            {
                mobs = {
                    bottomleft02 = {
                        { prefab = 'bearger', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 15 },
                    { prefab = 'icestaff', count = 1, },
                }
            },

            -- wave 7
            {
                mobs = {
                    middle02 = {
                        { prefab = 'shadow_rook', count = 1 },
                    },
                    topright02 = {
                        { prefab = 'shadow_bishop', count = 1 },
                    },
                    bottomleft02 = {
                        { prefab = 'shadow_knight', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 20 },
                    { prefab = 'townportaltalisman', count = 3, },
                }
            },

            -- wave 8
            {
                mobs = {
                    middle02 = {
                        { prefab = 'klaus', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 30 },
                    { prefab = 'yellowamulet', count = 1, },
                }
            },
            
            -- wave 9
            {
                mobs = {
                    middle02 = {
                        { prefab = 'smallbird', count = 1 },
                    },
                },
                loot = {
                    { prefab = 'goldnugget', count = 50 },
                    { prefab = 'tallbirdegg', count = 3, },
                    { prefab = 'townportal_blueprint', count = 1, },
                    { prefab = 'armor_sanity', count = 1, },
                    { prefab = 'nightsword', count = 1, },
                }
            },
        }
    },
}

return CTFBossFightInfo;
