---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 12:28 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function master_post_init(inst)
    inst.components.armor:SetTags(nil);
    inst.components.armor.GetAbsorption = function(self, attacker)
        if attacker and attacker:HasTag('bee') then
            return self.absorb_percent * CTF_ARMOUR.beehat.bee_absorption_mult;
        end
        return self.absorb_percent;
    end
end

CTFInit:Prefab('beehat', nil, master_post_init);
