---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 3:51 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function onAttacked(owner, data)
    local attacker = data.attacker;
    if attacker and attacker:IsValid() and attacker.components.health and attacker.components.combat and not attacker.components.health:IsDead() then
        local isRanged = data.weapon and (data.weapon:HasTag('projectile') or data.weapon:HasTag('rangedweapon'));
        if not isRanged then
            attacker.components.combat:GetAttacked(owner, CTF_ARMOUR.cookiecutterhat.return_damage);
        end
    end
end

local function master_post_init(inst)
    local OldOnEquip = inst.components.equippable.onequipfn;
    local OldOnUnequip = inst.components.equippable.onunequipfn;

    inst.components.equippable:SetOnEquip(function(f_inst, owner)
        OldOnEquip(f_inst, owner);
        f_inst:ListenForEvent('attacked', onAttacked, owner);
    end);

    inst.components.equippable:SetOnUnequip(function(f_inst, owner)
        OldOnUnequip(f_inst, owner);
        f_inst:RemoveEventCallback('attacked', onAttacked, owner);
    end);

end

CTFInit:Prefab('cookiecutterhat', nil, master_post_init);
