---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 12:00 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function OnBlocked(owner)
    owner.SoundEmitter:PlaySound('dontstarve/wilson/hit_scalemail');
end

local function onequip(inst, owner)
    local skin_build = inst:GetSkinBuild();
    if skin_build ~= nil then
        owner:PushEvent('equipskinneditem', inst:GetSkinName());
        owner.AnimState:OverrideItemSkinSymbol('swap_body', skin_build, 'swap_body', inst.GUID, 'torso_dragonfly');
    else
        owner.AnimState:OverrideSymbol('swap_body', 'torso_dragonfly', 'swap_body');
    end

    if owner.components.health ~= nil then
        owner.components.health.rawDamageModifiers:SetModifier(inst, CTF_ARMOUR.armordragonfly.raw_damage_multiplier);
    end

    inst:ListenForEvent('blocked', OnBlocked, owner);
    inst:ListenForEvent('attacked', OnBlocked, owner);
end

local function onunequip(inst, owner)
    owner.AnimState:ClearOverrideSymbol('swap_body');

    inst:RemoveEventCallback('blocked', OnBlocked, owner);
    inst:RemoveEventCallback('attacked', OnBlocked, owner);

    if owner.components.health ~= nil then
        owner.components.health.rawDamageModifiers:RemoveModifier(inst);
    end

    local skin_build = inst:GetSkinBuild();
    if skin_build ~= nil then
        owner:PushEvent('unequipskinneditem', inst:GetSkinName());
    end
end

local function master_post_init(inst)
    inst.components.equippable:SetOnEquip(onequip);
    inst.components.equippable:SetOnUnequip(onunequip);
end

CTFInit:Prefab('armordragonfly', nil, master_post_init);