---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 3:25 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function master_post_init(inst)
    inst.components.equippable.walkspeedmult = 1.0;
    inst:ListenForEvent('percentusedchange', function(f_inst, data)
        local speedMult = 1.0 + CTF_ARMOUR.footballhat.durability_speed_bonus * (1.0 - data.percent);
        inst.components.equippable.walkspeedmult = math.floor(speedMult * 100) / 100;
    end);
end

CTFInit:Prefab('footballhat', nil, master_post_init);
