---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-02 7:32 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function master_post_init(inst)
    inst.components.equippable.walkspeedmult = CTF_ARMOUR.armorgrass.walkspeedmult;
end

CTFInit:Prefab('armorgrass', nil, master_post_init);
