---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 12:03 a.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function NoHoles(pt)
    return not TheWorld.Map:IsPointNearHole(pt)
end

local function spawnTentacleChance(owner, data)
    if data.attacker and math.random() < CTF_ARMOUR.armorruins.tentacle_chance then
        local pt;
        
        if data.attacker:IsValid() then
            pt = data.attacker:GetPosition();
        else
            pt = owner:GetPosition();
            data.attacker = nil;
        end
        
        local offset = FindWalkableOffset(pt, math.random() * 2 * PI, 2, 3, false, true, NoHoles);
        if offset ~= nil then
            owner.SoundEmitter:PlaySound('dontstarve/common/shadowTentacleAttack_1');
            owner.SoundEmitter:PlaySound('dontstarve/common/shadowTentacleAttack_2');
            local tentacle = SpawnPrefab('shadowtentacle');
            if tentacle ~= nil then
                tentacle.Transform:SetPosition(pt.x + offset.x, 0, pt.z + offset.z);
                tentacle.components.combat:SetTarget(data.attacker);
            end
        end
    end
end

local function master_post_init(inst)
    local OldOnEquip = inst.components.equippable.onequipfn;
    local OldOnUnequip = inst.components.equippable.onunequipfn;

    inst.components.equippable:SetOnEquip(function(f_inst, owner)
        OldOnEquip(f_inst, owner);
        f_inst:ListenForEvent('attacked', spawnTentacleChance, owner);
    end);

    inst.components.equippable:SetOnUnequip(function(f_inst, owner)
        OldOnUnequip(f_inst, owner);
        f_inst:RemoveEventCallback('attacked', spawnTentacleChance, owner);
    end);
    
end

CTFInit:Prefab('armorruins', nil, master_post_init);
