---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-02 8:08 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');
local CTF_TEAM_CONSTANTS = use('scripts/constants/CTFTeamConstants');

local function master_post_init(inst)
    --shadow_teleport_out
    local OldOnEquip = inst.components.equippable.onequipfn;
    local OldOnUnequip = inst.components.equippable.onunequipfn;

    inst.components.equippable:SetOnEquip(function(f_inst, owner)
        OldOnEquip(f_inst, owner);
        if owner:HasTag(CTF_TEAM_CONSTANTS.TEAM_PLAYER_TAG) and owner.data and owner.data.ctf_team_tag then
            local teamTag = owner.data.ctf_team_tag;
            f_inst.components.equippable.ctf_task = f_inst:DoPeriodicTask(CTF_ARMOUR.armor_sanity.aoe_damage_period, function()
                owner:SpawnChild('shadow_teleport_out');
                -- delay the damage so it aligns better with the animation
                f_inst:DoTaskInTime(0.4, function()
                    local x, y, z = owner.Transform:GetWorldPosition();
                    local ents = TheSim:FindEntities(x, y, z, CTF_ARMOUR.armor_sanity.aoe_damage_radius, { '_combat', '_health' }, { teamTag });
                    for _, v in ipairs(ents) do
                        if v:IsValid() and not v:IsInLimbo() and not v.components.health:IsDead() then
                            v.components.combat:GetAttacked(owner, CTF_ARMOUR.armor_sanity.aoe_damage, f_inst);
                        end
                    end
                end);
            end);
        end
    end);

    inst.components.equippable:SetOnUnequip(function(f_inst, owner)
        OldOnUnequip(f_inst, owner);
        if f_inst.components.equippable.ctf_task then
            f_inst.components.equippable.ctf_task:Cancel();
            f_inst.components.equippable.ctf_task = nil;
        end
    end);
end

CTFInit:Prefab('armor_sanity', nil, master_post_init);
