---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 1:44 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function onAttacked(owner, data)
    local attacker = data.attacker;
    local vest = owner and owner.components.inventory and owner.components.inventory:GetEquippedItem(EQUIPSLOTS.BODY) or nil;
    if vest and vest.prefab == 'armorsnurtleshell' and attacker and attacker:IsValid() and attacker.components.locomotor then
        local isRanged = data.weapon and (data.weapon:HasTag('projectile') or data.weapon:HasTag('rangedweapon'));
        if not isRanged then
            if attacker.ctf_slurtlehat_slow_task ~= nil then
                attacker.ctf_slurtlehat_slow_task:Cancel()
            end

            attacker.ctf_slurtlehat_slow_task = attacker:DoTaskInTime(CTF_ARMOUR.slurtlehat.costume_slow_duration, function(i)
                i.components.locomotor:RemoveExternalSpeedMultiplier(i, 'slurtlehat');
                i.ctf_slurtlehat_slow_task = nil;
            end);

            attacker.components.locomotor:SetExternalSpeedMultiplier(attacker, 'slurtlehat', 1.0 - CTF_ARMOUR.slurtlehat.costume_slow_percent);
        end
    end
end

local function master_post_init(inst)
    local OldOnEquip = inst.components.equippable.onequipfn;
    local OldOnUnequip = inst.components.equippable.onunequipfn;

    inst.components.equippable:SetOnEquip(function(f_inst, owner)
        OldOnEquip(f_inst, owner);
        f_inst:ListenForEvent('attacked', onAttacked, owner);
    end);

    inst.components.equippable:SetOnUnequip(function(f_inst, owner)
        OldOnUnequip(f_inst, owner);
        f_inst:RemoveEventCallback('attacked', onAttacked, owner);
    end);

end

CTFInit:Prefab('slurtlehat', nil, master_post_init);
