---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-04-03 3:42 p.m.
---

local CTFInit = use('scripts/tools/CTFInit');
local CTF_ARMOUR = use('scripts/constants/CTFArmourConstants');

local function master_post_init(inst)
    inst.components.equippable.walkspeedmult = 1.0 + CTF_ARMOUR.wathgrithrhat.walk_speed_bonus;
end

CTFInit:Prefab('wathgrithrhat', nil, master_post_init);
