---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-21 1:38 p.m.
---

local require = GLOBAL.require;
local CTF_CONSTANTS = require('teams/CTFTeamConstants');
local PlayerStatusScreen = require('screens/playerstatusscreen');

local OldGetDisplayName = PlayerStatusScreen.GetDisplayName;
PlayerStatusScreen.GetDisplayName = function(self, clientrecord)
    local result = OldGetDisplayName(self, clientrecord);
    local teamID = CTFTeamManager:getUserTeamID(clientrecord.userid);
    if teamID ~= nil then
        -- patch the client color here
        clientrecord.colour = CTF_CONSTANTS.TEAM_COLORS[teamID];
        return '[T' .. teamID .. '] ' .. result;
    end

    return result;
end
