---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-09 9:44 p.m.
---

ACTIONS.CASTAOE.stroverridefn = function(act)
    if act.invobject and act.invobject.components and act.invobject.components.aoespell then
        return act.invobject.components.aoespell.str;
    end
    return nil;
end

ACTIONS.CASTAOE.fn = function(act)
    if act.invobject ~= nil and act.invobject.components.aoespell ~= nil and act.invobject.components.aoespell:CanCast(act) then
        act.invobject.components.aoespell:CastSpell(act)
        return true
    end
end

AddStategraphActionHandler('wilson', _G.ActionHandler(_G.ACTIONS.CASTAOE, function (inst, action)
    return action.invobject ~= nil and (action.invobject:HasTag('abigail_flower') and 'ctf_summon_abigail')
end));

AddStategraphActionHandler('wilson_client', _G.ActionHandler(_G.ACTIONS.CASTAOE, function (inst, action)
    return action.invobject ~= nil and (action.invobject:HasTag('abigail_flower') and 'ctf_summon_abigail')
end));
