---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-15 11:58 p.m.
---

Assets = {
    Asset('ATLAS', 'images/ctf_crafting_tabs.xml'),
    Asset('IMAGE', 'images/ctf_crafting_tabs.tex'),
}

PrefabFiles = {
    'ctf_team_marker',
}
