---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-15 11:58 p.m.
---

Assets = {
    Asset('ATLAS', 'images/ctf_crafting_tabs.xml'),
    Asset('IMAGE', 'images/ctf_crafting_tabs.tex'),

    Asset('ANIM', 'anim/ctf_spider_team1.zip'),
    Asset('ANIM', 'anim/ctf_spider_team2.zip'),
}

PrefabFiles = {
    'ctf_team_marker',
    'ctf_player_net',
    'ctf_abigail_hit',
}
