---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-15 11:58 p.m.
---

local Assets = {
    Asset('ATLAS', 'images/ctf_crafting_tabs.xml'),
    Asset('IMAGE', 'images/ctf_crafting_tabs.tex'),
}

if not TheNet:IsDedicated() then
    RegisterPrefabs(Prefab('MOD_WARSAK_ASSETS', function() end, Assets, nil));
    TheSim:LoadPrefabs({ 'MOD_WARSAK_ASSETS' });
end

PrefabFiles = {
    'ctf_team_marker',
    'ctf_player_net',
    'ctf_abigail_hit',
}
