---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-17 8:36 p.m.
---

local CTF_STRINGS = use('scripts/constants/CTFStrings');

local itemsList = TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT;
local gold12x = {
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
};

for k, _ in pairs(itemsList) do
    itemsList[k] = gold12x;
end

AddPrefabPostInit('world', function(inst)
    for k, v in pairs(CTF_STRINGS.CHARACTER_DESCRIPTIONS) do
        STRINGS.CHARACTER_DESCRIPTIONS[k] = v;
    end
end);
