---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-17 8:36 p.m.
---

local itemsList = TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT;
local gold12x = {
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
    'goldnugget',
};

for k, _ in pairs(itemsList) do
    itemsList[k] = gold12x;
end


STRINGS.CHARACTER_DESCRIPTIONS.wilson = 'I shall take your life force and use it to grow my stubble'; -- 'WORK IN PROGRESS'; -- '\n*Is a well rounded character';
STRINGS.CHARACTER_DESCRIPTIONS.willow = 'WORK IN PROGRESS'; -- '*Can deploy bernie to battle';
STRINGS.CHARACTER_DESCRIPTIONS.wendy = '*Can use Abigail for a quick burst of damage\n*Abigails health becomes her damage\n*Resets after each use';
STRINGS.CHARACTER_DESCRIPTIONS.wolfgang = '*Absorbs damage when full\n*Gets slower on a full stomach\n*Is a literal tank';
STRINGS.CHARACTER_DESCRIPTIONS.wx78 = '*Can buy gears to upgrade from the store\n*Can get very tanky';
STRINGS.CHARACTER_DESCRIPTIONS.wickerbottom = '*Can craft Heart Tart Art\n*Can also craft Humpty Dumpty';
STRINGS.CHARACTER_DESCRIPTIONS.wes = '*Armor effectiveness reduced\n*Does more damage\n*Has 75 health, hunger and sanity';
STRINGS.CHARACTER_DESCRIPTIONS.waxwell = '*Can spawn up to 5 shadow duelists';
STRINGS.CHARACTER_DESCRIPTIONS.woodie = '*Can transform into the weremoose';
STRINGS.CHARACTER_DESCRIPTIONS.woodie_us = '*Can transform into the weremoose\n*Will beat you in hockey';
STRINGS.CHARACTER_DESCRIPTIONS.woodie_canada = '*Can transform into the weremoose\n*Comes from the true north\n*Oh Ca.na.daaaa...';
STRINGS.CHARACTER_DESCRIPTIONS.wathgrithr = '*Same old, same old';
STRINGS.CHARACTER_DESCRIPTIONS.webber = '*Can be played as a tank\n*Takes less damage from spiders';
STRINGS.CHARACTER_DESCRIPTIONS.winona = '*Can build catapults\n*And generators\n*And craft gems';
STRINGS.CHARACTER_DESCRIPTIONS.wortox = '*Souls drop by last hitting enemy players\n*Also beehives and pigs\n*Cannot soulhop when wearing the piggyback';
STRINGS.CHARACTER_DESCRIPTIONS.wormwood = '*Can craft bramble items\n*And compost wrap';
STRINGS.CHARACTER_DESCRIPTIONS.warly = '*Can build a seasoning station\n*Crafts spices\n*Why not add some flavor to food?!';
STRINGS.CHARACTER_DESCRIPTIONS.wurt = 'WORK IN PROGRESS'; -- '*Buy merm king\n*And guards';
STRINGS.CHARACTER_DESCRIPTIONS.walter = '*Get a slingshot from the shop\n*Ammo can be bought too';
STRINGS.CHARACTER_DESCRIPTIONS.random = 'Who will you be?';