---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-21 5:08 p.m.
---

local require = _G.require;
local CTF_STRINGS = require('constants/CTFStrings');
local CTF_TEAM_CONSTANTS = require('constants/CTFTeamConstants');
local UserCommands = require('usercommands');
local ChatInputScreen = require('screens/chatinputscreen');
local ChatQueue = require('widgets/chatqueue');

ChatInputScreen.Run = function(self)
    local chat_string = self.chat_edit:GetString();
    chat_string = chat_string ~= nil and chat_string:match('^%s*(.-%S)%s*$') or '';
    if chat_string == '' then
        return
    elseif string.sub(chat_string, 1, 1) == '/' then
        UserCommands.RunTextUserCommand(string.sub(chat_string, 2), ThePlayer, false);
    elseif chat_string:utf8len() <= MAX_CHAT_INPUT_LENGTH then
        local prefix;
        local player = CTFTeamManager:getCTFPlayer(ThePlayer.userid);
        local teamID = player and player:getTeamID() or 0;
        if self.whisper and teamID ~= 0 then
            prefix = CTF_STRINGS.CHAT_TEAM_DELIMITER .. CTFTeam:makeTeamTag(teamID) .. CTF_STRINGS.CHAT_TEAM_DELIMITER;
        else
            prefix = '';
        end
        TheNet:Say(prefix .. chat_string, false);
    end
end

local OldDoInit = ChatInputScreen.DoInit;
ChatInputScreen.DoInit = function(self)
    OldDoInit(self);
    if self.chat_type then
        if self.whisper then
            self.chat_type:SetString(CTF_STRINGS.CHAT_TEAM);
        else
            self.chat_type:SetString(CTF_STRINGS.CHAT_ALL);
        end
    end
end

--ChatQueue.OnMessageReceived = function(self, name, prefab, message, colour, whisper, profileflair)
--    --Make sure that we use the default profile flair is the user hasn't set one.
--    if profileflair == nil then
--        profileflair = 'default';
--    end
--
--    local prefix = whisper and CTF_STRINGS.CHAT_TEAM_SHORT or CTF_STRINGS.CHAT_ALL_SHORT;
--    local displayName = prefix .. ' ' .. self:GetDisplayName(name, prefab);
--    self:PushMessage(displayName, message, colour, false, false, profileflair);
--end

local OldNetworking_Say = GLOBAL.Networking_Say;
GLOBAL.Networking_Say = function(guid, userid, name, prefab, message, colour, whisper, isemote, user_vanity)
    if not message then
        return;
    end
    
    local player = CTFTeamManager:getCTFPlayer(userid);
    local teamID = player and player:getTeamID() or 0;
    if teamID ~= 0 then
        colour = CTF_TEAM_CONSTANTS.TEAM_COLORS[teamID];
    end

    local teamTag = string.match(message, CTF_STRINGS.CHAT_TEAM_DELIMITER .. '(.+)' .. CTF_STRINGS.CHAT_TEAM_DELIMITER);
    if teamTag then
        message = string.match(message, CTF_STRINGS.CHAT_TEAM_DELIMITER .. '.+' .. CTF_STRINGS.CHAT_TEAM_DELIMITER .. '(.+)');
        if ThePlayer and ThePlayer:HasTag(teamTag) then
            if name then
                name = CTF_STRINGS.CHAT_TEAM_SHORT .. ' ' .. name;
            end
            OldNetworking_Say(guid, userid, name, prefab, message, colour, false, isemote, user_vanity);
        end
    else
        if name then
            name = CTF_STRINGS.CHAT_ALL_SHORT .. ' ' .. name;
        end
        OldNetworking_Say(guid, userid, name, prefab, message, colour, whisper, isemote, user_vanity);
    end
end
