---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-03-22 8:09 p.m.
---

modimport('scripts/components/patcher/burnable');
modimport('scripts/components/patcher/equippable_replica');
modimport('scripts/components/patcher/weapon');
modimport('scripts/components/patcher/health');
