---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-15 12:22 p.m.
---

local CTF_STRINGS = use('scripts/constants/CTFStrings');

AddPrefabPostInit('world', function(inst)
    for k, v in pairs(CTF_STRINGS.CRAFTING_DESCRIPTIONS) do
        STRINGS.RECIPE_DESC[k] = v;
    end
end);
