---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-17 11:52 a.m.
---

local function registerRecipes(content)
    for _, v in ipairs(content) do
        -- AddRecipeTab = function( rec_str, rec_sort, rec_atlas, rec_icon, rec_owner_tag, rec_crafting_station )
        -- WAR =           { str = "WAR",          sort = 5,   icon = "tab_fight.tex" },
        local recipe_tab = AddRecipeTab(
                v.tab,
                v.order,
                nil,
                v.icon,
                nil,
                nil
        );

        -- AddRecipe = function(arg1, ...)
        -- Recipe("spear", {Ingredient("twigs", 2), Ingredient("rope", 1), Ingredient("flint", 1) }, RECIPETABS.WAR,  TECH.SCIENCE_ONE)
        -- (name, ingredients, tab, level, placer, min_spacing, nounlock, numtogive, builder_tag, atlas, image)
        for _, vv in ipairs(v.recipes) do
            AddRecipe(vv.prefab, vv.ingredients, recipe_tab, vv.level, nil, nil, nil, vv.count);
        end
    end
end

local function buildNewCrafting()
    local content = {
        {
            tab = 'Fight',
            order = -1,
            icon = 'tab_fight.tex',
            recipes = {
                {
                    prefab = 'spear',
                    ingredients = { Ingredient('goldnugget', 10) },
                    count = 1
                },
				{
                    prefab = 'boomerang',
                    ingredients = { Ingredient('goldnugget', 15) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'whip',
                    ingredients = { Ingredient('goldnugget', 15) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'cookiecutterhat',
                    ingredients = { Ingredient('goldnugget', 15) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'footballhat',
                    ingredients = { Ingredient('goldnugget', 15) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'armorwood',
                    ingredients = { Ingredient('goldnugget', 15) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'tentaclespike',
                    ingredients = { Ingredient('goldnugget', 15), Ingredient('spear', 1) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'spear_wathgrithr',
                    ingredients = { Ingredient('goldnugget', 15), Ingredient('spear', 1) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'hambat',
                    ingredients = { Ingredient('goldnugget', 20), Ingredient('spear_wathgrithr', 1) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'wathgrithrhat',
                    ingredients = { Ingredient('goldnugget', 20), Ingredient('footballhat', 1) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'armormarble',
                    ingredients = { Ingredient('goldnugget', 20), Ingredient('armorwood', 1) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
            }
        },
		{
            tab = 'Food',
            order = -2,
            icon = 'tab_farm.tex',
            recipes = {
                {
                    prefab = 'jellybean',
                    ingredients = { Ingredient('goldnugget', 2) },
                    count = 1
                },
				{
                    prefab = 'cookedmeat',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'bird_egg_cooked',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'dragonfruit_cooked',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'potato_cooked',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'garlic_cooked',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'carrot_cooked',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'butterflywings',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
				{
                    prefab = 'honey',
                    ingredients = { Ingredient('goldnugget', 3) },
                    level = TECH.SCIENCE_ONE,
                    count = 1
                },
            }
        },
    }

    registerRecipes(content);
end

AddPrefabPostInit('world', function()
    RemoveAllRecipes();
    buildNewCrafting();
end);
