---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-02-07 11:13 p.m.
---

local require = _G.require;
local LootDropper = require('components/lootdropper');

local LOOT_TABLE = {
    bishop_nightmare = { gold = 5 },
    killerbee = { gold = 1 },
    merm = { gold = 6 },
    pigguard = { gold = 4 },
    spider = { gold = 1 },
    spider_warrior = { gold = 2 },
    spiderden = { gold = 4 },
    spiderqueen = { gold = 20 },
    tallbird = { gold = 3 },
    wasphive = { gold = 4 },
    skeleton_player = { gold = 5 },
    molebat = { gold = 2 },
    koalefant_summer = { gold = 40 },
    worm = { gold = 3 },
    bishop = { gold = 5 },
    krampus = { gold = 3 },
    knight_nightmare = { gold = 5 },
    mutated_penguin = { gold = 3 },
    

    -- Secret Fight
    frog = { other = { 'spider_dropper', }, gold = 1 },
    spider_dropper = { other = { 'walrus', }, gold = 2 },
    walrus = { other = { 'knight', }, gold = 3 },
    knight = { other = { 'mutated_penguin', 'mutated_penguin', 'penguin', 'mutated_penguin', 'mutated_penguin', }, gold = 4 },
    penguin = { other = { 'leif', }, gold = 5 },
    leif = { other = { 'warg', }, gold = 6 },
    warg = { other = { 'deerclops', }, gold = 7 },
    deerclops = { other = { 'rabbit', }, gold = 8 },
    rabbit = { other = { 'tallbirdegg', 'tallbirdegg', 'tallbirdegg', 'beemine', 'beemine', 'beemine', 'beemine', 'beemine', 'cane', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'greenamulet', }, gold = 80 },

    -- Other Secret Fight (Maze)
    bat = { other = { 'spider_spitter', }, gold = 10 },
    spider_spitter = { other = { 'koalefant_winter', 'cane', }, gold = 3 },
    koalefant_winter = { other = { 'worm', 'worm', 'slurtle', 'greenstaff', }, gold = 3 },
    slurtle = { other = { 'spat', 'orangeamulet', }, gold = 5 },
    spat = { other = { 'rook', 'bishop', 'eyeturret_item', }, gold = 5 },
    rook = { other = { 'glommer', 'yellowamulet', }, gold = 10 },
    glommer = { other = { 'knight_nightmare', 'knight_nightmare', 'knight_nightmare', 'rook_nightmare', }, gold = 10 },
    rook_nightmare = { other = { 'bearger', 'townportaltalisman', }, gold = 10 },
    bearger = { other = { 'carrat', 'townportaltalisman', 'townportaltalisman', }, gold = 10 },
    carrat = { other = { 'tallbirdegg', 'tallbirdegg', 'tallbirdegg', 'beemine', 'beemine', 'beemine', 'beemine', 'beemine', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'waterplant_bomb', 'greenamulet', 'townportal_blueprint', 'townportaltalisman_blueprint', }, gold = 50 },
};

LootDropper.DropLoot = function(self, pt)
    local prefabs;
    if self.inst and self.inst.prefab and LOOT_TABLE[self.inst.prefab] then
        prefabs = LOOT_TABLE[self.inst.prefab];
    else
        prefabs = { gold =  1 };
    end

    if prefabs.gold then
        for _ = 1, prefabs.gold do
            self:SpawnLootPrefab('goldnugget', pt)
        end
    end

    if prefabs.other then
        for _, v in ipairs(prefabs.other) do
            self:SpawnLootPrefab(v, pt)
        end
    end

    TheWorld:PushEvent("entity_droploot", { inst = self.inst });
end
