---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by darionco.
--- DateTime: 2021-01-17 12:05 p.m.
---

local function removeAllItems(player)
    for _,v in pairs(player.components.inventory.itemslots) do
        v:Remove();
    end
end

local function putInInventory(player, prefab, count)
    for i = 1, count do
        player.components.inventory:GiveItem(SpawnPrefab(prefab))
    end
end

local function initializeInventory(player)
    putInInventory(player, 'goldnugget', 12);
end

return {
    removeAllItems = removeAllItems,
    putInInventory = putInInventory,
    initializeInventory = initializeInventory,
}
